### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gavinhungry** [arigit/lastwake.py#1]
Hi,

I've added this the Arch Linux User Repository (AUR) here:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lastwake-git

I've listed the license as `unknown`, since I couldn't find any licenses listed in your repository. Let me know and I will update it.

**Comment by arigit** [comment]
Thanks for packaging it.

Added license - GPL v3

**Comment by gavinhungry** [comment]
Thanks, updated.
