### ISSUE TITLE
Sleep wake up detection in Ubuntu 22.04 Jammy

### ISSUE THREAD

**Issue by hossein** [arigit/lastwake.py#15]
Hello, thanks for the useful utility!

In Ubuntu 22.04 (kernel 5.15, systemd 249.11) the sleep wake up message looks like the following:

```
ACPI: PM: Waking up from system sleep state S3
```

But this package expects the following string, which worked in Ubuntu 21.10 (kernel 5.13, systemd 248.3):

```
ACPI: Waking up from system sleep state S3
```

It's easy to change the match string to make this work, but I can't verify if not including the `ACPI:` or `PM:` prefix in the match string is fine on all systems.

**Comment by arigit** [comment]
Good catch, thanks for the report. I have systems in both 22.04 and 20.04, I'll try to reproduce shortly and then test with a shortened string

**Comment by arigit** [comment]
this is fixed in the last commit. Thanks for the report!
