### ISSUE TITLE
After upgrading to Debian 12, script stops working

### ISSUE THREAD

**Issue by hoclun-rigsep** [arigit/lastwake.py#16]
```
Traceback (most recent call last):
  File "/tmp/lastwake.py/./lastwake.py", line 173, in <module>
    secondsSinceLastWakeUp = (end - start).total_seconds()
                              ~~~~^~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by arigit** [comment]
Can you try changing line 171 to:

```
end = datetime.datetime.now(tz=datetime.timezone.utc)
```

and retest?

**Comment by hoclun-rigsep** [comment]
> Can you try changing line 171 to: ``` end = datetime.datetime.now(tz=datetime.timezone.utc) ``` and retest?

This works. Thank you.

**Comment by arigit** [comment]
@hoclun-rigsep  can you please test again with the latest version? it should handle both your case/recent debian and older debian/ubuntu versions as well

**Comment by hoclun-rigsep** [comment]
Ok, I am running nothing-special Debian 12. I ran lastwake.py with latest and my output was as follows, which is not good because the system has suspended and awoken many times since boot:

```

Wake/Sleep Time SystemD Journal Analyzer

 Boot under analysis: current boot
 Initial Boot Timestamp:  2023-10-01 11:56:32

   Wake Timestamp    |   Sleep Timestamp   | Awake Time | Wake From
 ------------------- | ------------------- | ---------- | ---------
 2023-10-01 11:56:32 |    (Still Awake)    |  387h 34m  | S5 (boot)
 ------------------- | ------------------- | ---------- | ---------

Days Since Boot: 16.15 - Days Awake: 16.15 - Wake/Sleep Cycles: 0
```

**Comment by arigit** [comment]
it sounds like the journal messages for system sleep/hibernate events may
have changed in newer systemd versions.

These are the messages that lastwake is interested on and needs:

    # Kernel messages lingo: Hibernation = to disk; Suspend = to RAM;
    # Sleep = either hibernation (S4) or suspend (S3)
    suspendStart = "Reached target Sleep."
    hibernateStart = "Suspending system..."
    suspendWakeList = ["ACPI: PM: Waking up from system sleep state S3",
"ACPI: Waking up from system sleep state S3"]
    hibernateWakeList = ["ACPI: PM: Waking up from system sleep state S4",
"ACPI: Waking up from system sleep state S4"]
    shuttingDown = "Shutting down."
    # Starting Sleep (applies to both Suspend and Hibernation): Suspending
system...

If you can, please take a look at your system journal and share what
messages you see when your system sleeps / hibernate  and when it wakes up
from either state.

Also please share with us what version of systemd you are using, eg:
> systemctl --version
>>> systemd 249 (249.11-0ubuntu3.10)

**Comment by hoclun-rigsep** [comment]
will do

**Comment by hoclun-rigsep** [comment]
Stock Debian 12 on amd64, `systemctl --version` says:

```
systemd 252 (252.12-1~deb12u1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

`journalctl` gives me messages like:

```
Entering sleep state 'suspend'...
System returned from sleep state.
```

I tried patching to look for these messages but I ran out of time. I'll take another crack if I can.

**Comment by hoclun-rigsep** [comment]
This seems to work; note that I didn't address hibernation at all.

```diff
diff --git a/lastwake.py b/lastwake.py
index 032771f..742fd91 100755
--- a/lastwake.py
+++ b/lastwake.py
@@ -99,15 +99,15 @@ if __name__ == '__main__':
 
     # Kernel messages lingo: Hibernation = to disk; Suspend = to RAM;
     # Sleep = either hibernation (S4) or suspend (S3)
-    suspendStart = "Reached target Sleep."
-    hibernateStart = "Suspending system..."
+    suspendStart = ['Entering sleep state \'suspend\'...', "Reached target Sleep."]
+    hibernateStart = ["Suspending system..."]
     suspendWakeList = ["ACPI: PM: Waking up from system sleep state S3", "ACPI: Waking up from system sleep state S3"]
     hibernateWakeList = ["ACPI: PM: Waking up from system sleep state S4", "ACPI: Waking up from system sleep state S4"]
     shuttingDown = "Shutting down."
     # Starting Sleep (applies to both Suspend and Hibernation): Suspending system...
 
 
-    for item in ([hibernateStart] + [suspendStart] + suspendWakeList + hibernateWakeList + [shuttingDown]):
+    for item in (hibernateStart + suspendStart + suspendWakeList + hibernateWakeList + [shuttingDown]):
         j.add_match("MESSAGE=" + item)
         j.add_disjunction()
 
@@ -131,7 +131,7 @@ if __name__ == '__main__':
         except:
             continue
         #print(str(entry['__REALTIME_TIMESTAMP'] )+ ' ' + entry['MESSAGE'])
-        if suspendStart in msg or hibernateStart in msg or shuttingDown in msg:
+        if any([i in msg for i in suspendStart]) or any([i in msg for i in hibernateStart]) or shuttingDown in msg:
             sleepCandidate = entry['__REALTIME_TIMESTAMP']
         elif  ( any(x in msg for x in (suspendWakeList + hibernateWakeList))
             and sleepCandidate is not None ):
```

**Comment by arigit** [comment]
Thanks. This did not break hibernation detection in older debian/ubuntu installs. Later this year when I upgrade my desktop to 24.04 I will address hibernation if needed



   Wake Timestamp    |   Sleep Timestamp   | Awake Time | Wake From
 ------------------- | ------------------- | ---------- | ---------
 2024-01-07 18:32:37 | 2024-01-07 19:35:30 |    1h  2m  | S5 (boot)
 2024-01-07 21:05:36 | 2024-01-07 21:08:00 |    0h  2m  | S3 (RAM) 
 2024-01-08 18:21:11 | 2024-01-09 21:36:04 |   27h 14m  | S4 (disk)
 2024-01-09 23:06:10 | 2024-01-09 23:09:00 |    0h  2m  | S3 (RAM) 
 2024-01-10 18:34:53 |    (Still Awake)    |    0h 20m  | S4 (disk)
 ------------------- | ------------------- | ---------- | --------- 

I'll merge the changes
